version: '3.1'

services:
  app:
    container_name: schedule-api
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres:9.5-alpine
    restart: always
    container_name: schedule-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initd/init.sql
