version: '3.1'

services:
  db:
    image: postgres:9.5-alpine
    restart: always
    container_name: schedule-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initd/init.sql
